#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — Halion Lab go-live: Vercel deploy + personal domain
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=8

banner "Halion Lab — go live (Vercel + your domain)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight — what ships is what's committed"
say "Deploying repo HalionLab/Sitekit, branch halion-lab-site."
warn "site.config.ts still has PLACEHOLDER contact info (phone, email, street"
warn "address). It renders in the footer and the site's structured data."
say ""
step "Fine to launch with placeholders and fix later — or Ctrl-C now,"
step "have Claude swap in the real contact details, push, and re-run this."
if confirm "Continue with the current committed state?"; then
  say "Onward."
else
  say "No problem — fix the config, push, and re-run: bash scripts/go-live.sh"
  exit 0
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Vercel account"
say "Vercel's free Hobby tier is enough for this site."
open_url "https://vercel.com/signup"
step "Choose 'Continue with GitHub' and authorize Vercel."
step "If you already have an account, just log in instead."
note "Use the GitHub account that can access the HalionLab org."
pause "Logged in to Vercel?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Import the repo"
open_url "https://vercel.com/new"
step "Under 'Import Git Repository', find HalionLab/Sitekit."
note "If it's not listed: 'Adjust GitHub App Permissions' → grant access to"
note "the HalionLab org (or the Sitekit repo) → it appears in the list."
step "Click Import. Framework shows 'Next.js' automatically — change nothing."
step "No environment variables are needed. Click Deploy."
note "This first deploy builds the 'main' branch — the generic Summit"
note "Services template. That's expected; your site arrives next stage."
pause "Deploy finished (confetti screen)?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Production branch → halion-lab-site"
say "Point production at your site branch instead of main."
step "Open the new project's dashboard → Settings → Git"
note "(if your dashboard shows it under Settings → Environments → Production,"
note "use that — Vercel has shown this in both places)."
step "Set 'Production Branch' to: halion-lab-site   → Save."
step "Go to the Deployments tab → open the ⋯ menu on the latest deployment"
step "→ Redeploy (or just wait: the next git push also triggers it)."
step "When it finishes, copy the production URL (something.vercel.app)."
ask VERCEL_DEPLOY_URL "Paste the production URL (https://...vercel.app):"
write_env VERCEL_DEPLOY_URL "$VERCEL_DEPLOY_URL"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Smoke-check the deployment"
open_url "$VERCEL_DEPLOY_URL"
step "You should see the dark Halion Lab homepage — sphere, particles, cards."
step "Spot-check /blog and /contact load too."
if confirm "Does the deployed site look right?"; then
  say "Good — the engine is live. Now the domain."
else
  warn "If it shows the Summit Services template, the production branch is"
  warn "still main — redo stage 4. Otherwise check the build logs in Vercel."
  pause "Sorted? (Enter to continue anyway)"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Add your domain in Vercel"
ask HALION_DOMAIN "Your domain, bare, no https:// (e.g. halionlab.com):"
write_env HALION_DOMAIN "$HALION_DOMAIN"
step "Project dashboard → Settings → Domains → Add."
step "Enter: $HALION_DOMAIN  → Add. Accept the recommended www redirect"
step "option if offered (www.$HALION_DOMAIN → $HALION_DOMAIN)."
step "Vercel now shows the exact DNS records it needs — usually an A record"
step "for the apex and a CNAME for www. KEEP THIS SCREEN OPEN."
note "Classic values are A @ → 76.76.21.21 and CNAME www → cname.vercel-dns.com,"
note "but ALWAYS use exactly what your Vercel screen shows — it varies."
pause "Domain added and DNS instructions visible?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "DNS records at your registrar"
say "Now the other half, at wherever you bought $HALION_DOMAIN"
say "(Namecheap, GoDaddy, Cloudflare, Porkbun, ...)."
step "Log in to your registrar → DNS settings / DNS records for the domain."
step "Add the record(s) exactly as the Vercel Domains screen shows:"
step "  - the A record on the apex (@)"
step "  - the CNAME on www"
step "Delete any OLD A/CNAME records on @ and www (registrar parking pages)."
note "Back on Vercel's Domains screen, the domain flips to a checkmark once"
note "DNS propagates — usually minutes, occasionally up to a few hours."
note "SSL is automatic after that; nothing to configure."
pause "Records saved at the registrar?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Canonical URL + final checks"
say "Tell the site its real address (feeds sitemap, OG tags, JSON-LD)."
step "Vercel project → Settings → Environment Variables → Add:"
step "  Key:   NEXT_PUBLIC_SITE_URL"
step "  Value: https://$HALION_DOMAIN     (Production environment)"
step "Save, then Deployments → ⋯ → Redeploy one more time."
write_env NEXT_PUBLIC_SITE_URL "https://$HALION_DOMAIN"
note "(Also saved locally so dev matches prod. Alternatively have Claude set"
note "url: 'https://$HALION_DOMAIN' in site.config.ts permanently.)"
pause "Env var set and redeployed?"
open_url "https://$HALION_DOMAIN"
step "Check: padlock (SSL), homepage, /blog, /contact, /sitemap.xml."
say ""
say "Remaining by-hand items you already know about:"
note "  - real phone/email/address in site.config.ts (if you kept placeholders)"
note "  - community wall tiles — swap for real media when ready"

finish
say "Halion Lab is live at https://$HALION_DOMAIN — ship often."
